In [1]:
import numpy as np

In [2]:
# 定义向量
x = np.array([2, 5, 8])
print(x)
print(x.shape)

[2 5 8]
(3,)


In [3]:
# 向量转置
print(x.T)
print(x.shape)

[2 5 8]
(3,)


In [4]:
# 相加
y = np.array([1, 3, 7])
print(x + y)

[ 3  8 15]


In [5]:
# 向量与标量相乘
print(x * 3)

[ 6 15 24]


In [6]:
# 向量与向量相乘 (对应位置元素相乘)
print(x * y)

[ 2 15 56]


In [7]:
# 向量点乘
# np.dot(x, y)
# x @ y
print(x.dot(y))

73


In [9]:
# 计算范数
l0_norm = np.linalg.norm(x, ord=0)
print(l0_norm)
l1_norm = np.linalg.norm(x, ord=1)
print(l1_norm)
l2_norm = np.linalg.norm(x, ord=2)
print(l2_norm)

3.0
15.0
9.643650760992955
