In [1]:
import numpy as np

In [2]:
print(6)
print('hello world')

6
hello world


In [3]:
print(np.sqrt(9))
print(np.exp(1))

3.0
2.718281828459045


In [4]:
# 累积和 累积积   #cummax() 累积大
arr = np.array([1, 2, 3])
print(np.cumsum(arr))  # 1 1+2 1+2+3
print(np.cumprod(arr))  # 1 1*2 1*2*3

[1 3 6]
[1 2 6]


In [5]:
x = np.arange(9.).reshape(3, 3)
print(x)
y = np.where(x > 3)
print(y)  # 返回满足条件的行索引与列索引(有点类似于横纵坐标)
print(x[y])  # 使用这些索引来获取满足条件的元素
print('\n')

a = np.array([[30, 40, 0], [0, 20, 10], [50, 0, 60]])
print(a)
print(np.nonzero(a))  # 返回非零元素的行索引与列索引

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))
[4. 5. 6. 7. 8.]


[[30 40  0]
 [ 0 20 10]
 [50  0 60]]
(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))


In [6]:
# 自定义条件
# print(np.where(条件,满足条件的,不满足条件的))
arr = np.array([1, 7, 4, 3, 6])
print(np.where(arr > 3, arr, '不满足'))

['不满足' '7' '4' '不满足' '6']


In [7]:
score = np.random.randint(50, 100, 10)
print(score)
print(np.where(score >= 60, '及格', '不及格'))

[97 63 56 95 72 74 98 72 71 75]
['及格' '及格' '不及格' '及格' '及格' '及格' '及格' '及格' '及格' '及格']


In [8]:
print(np.where(
    score < 60, '不及格', np.where(
        score > 80, '优秀', '及格'
    )
))  # 嵌套

['优秀' '及格' '不及格' '优秀' '及格' '及格' '优秀' '及格' '及格' '及格']


In [9]:
# np.select(条件,返回值,default='缺省值')
print(np.select([score < 60, score > 80], ['不及格', '优秀'], default='及格'))

['优秀' '及格' '不及格' '优秀' '及格' '及格' '优秀' '及格' '及格' '及格']


In [10]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
print(arr3.shape)
print(arr3.reshape((3, 2), order='F'))  # F按列 默认C按行

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 5]
 [4 3]
 [2 6]]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# 过滤器数组
filter_arr = arr % 2 == 0
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[False  True False  True False  True False]
[2 4 6]


In [12]:
arr = np.random.randint(0,20,(5,5))
print(arr)

[[ 5 14 10  4 19]
 [ 0  9  3 12  5]
 [15  2 12 18  5]
 [14  4  0  5 11]
 [17  3 12 14  7]]
